```typescript
// ...existing code...
            { path: 'relatorio', component: ReportComponent, canActivate: [roleGuard], data: { roles: ['ALUNO','PRECEPTOR','ADMIN','COORDENADOR'] } },
// ...existing code...
```